packages:
  - 'example_1_zod_validation'
  - 'example_2_zod_vercel'

catalog:
  "typescript": 5.5.4
  "vite": 5.3.5
  "vite-plugin-checker": ^0.7.2
  "vite-tsconfig-paths": ^4.3.2
  "@liuli-util/vite-plugin-node": ^0.9.0
  "zod": ^3.23.8
  "@types/node": ^22.5.4
  "@types/turndown": ^5.0.5
  "turndown": ^7.2.0
  "ai": ^3.3.3
  "dotenv": ^16.4.5
  "@ai-sdk/openai": ^0.0.55
  "tsx": ^4.19.0